# Generated by Django 5.0.6 on 2024-07-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories_eaten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalexercise',
            name='calories_burned_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalfood',
            name='calories_eaten_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
