# Generated by Django 5.0.6 on 2024-07-07 02:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_alter_exercise_calories_burned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalfood',
            name='user',
        ),
        migrations.RemoveField(
            model_name='food',
            name='calories_eaten',
        ),
        migrations.AddField(
            model_name='food',
            name='calories_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=100, null=True)),
                ('goal_calories_eaten_per_day', models.IntegerField(default=0)),
                ('goal_calories_burned_per_day', models.IntegerField(default=0)),
                ('goal_weight', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_name', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GoalExercise',
        ),
        migrations.DeleteModel(
            name='GoalFood',
        ),
    ]
